### PR TITLE
MvdM's fixes

### LINKED ISSUE #10: Issue with how orbit functions are stored in KerrGeoOrbitFunction (and related)
There is an issue with how the coordinate functions (t, r, theta, phi) are currently stored inside the 'KerrGeoOrbitFunction' object. Currently, these are generated inside a module using a DelayedSet definition assigning the function to the appropriate symbols, which have been localized using Module. The symbols are then passed to the resulting 'KerrGeoOrbitFunction' object.

The consequence of this is that the actual function definitions are not stored as part of the 'KerrGeoOrbitFunction' object, but as an DownValue of the temporary symbols generated by the Module. Although this works it has a number of downsides:

- The symbols with the function definitions have the 'Temporary' attribute, which makes them vulnerable to aggressive thrash collection solutions (which may be necessary because of various Mathematica memory leak issues).
- The function definitions will not be stored when attempting to stored a 'KerrGeoOrbitFunction' object to disk using 'Put'.
- Issues may arise when using the  'KerrGeoOrbitFunction' object with parallel kernels because the function definitions may not be distributed to the parallel kernels. (For example, when the orbit was not generate in the Global` context.

One way to avoid this is by using "pure functions" to define the orbital functions. E.g. instead of defining the t component using:

   t[\[Lambda]_]:= qt0 + \[CapitalUpsilon]t \[Lambda] + tr[\[CapitalUpsilon]r \[Lambda] + qr0] + tz[\[CapitalUpsilon]\[Theta] \[Lambda] + qz0]-Ct;

It could be defined using:

t = Function[\[Lambda],
   Evaluate[
       qt0 + \[CapitalUpsilon]t \[Lambda] + tr[\[CapitalUpsilon]r \[Lambda] + qr0] + tz[\[CapitalUpsilon]\[Theta] \[Lambda] + qz0]-Ct
   ]
]

(note the use of 'Evaluate' inside the function definition).

### LINKED ISSUE #14: Frequencies associated with a KerrGeoOrbit
Querying a `KerrGeoOrbitFunction` for the orbital frequencies should return an Association and not a list. This would be inline with the behaviour of the `KerrGeoFrequencies` function. This also helps to make it clear which frequencies being calculated.

As an example: 

`orbit = KerrGeoOrbit[0.9, 10, 0.5, 0.5]`
`orbit["Frequencies"]` 

Returns `{2.69806, 3.6425, 3.84269}`

Where as `KerrGeoFrequencies[0.9, 10, 0.5, 0.5, Time -> "Mino"]` returns
`<|"\[CapitalUpsilon]_r" -> 2.69806, "\[CapitalUpsilon]\)_\[Theta]" -> 
  3.6425, "\[CapitalUpsilon]_\[Phi]" -> 3.84269|>`

(I've removed the SubscriptBox from the above example for clarity)

### PR DESCRIPTION
**Pull request by MvdMeent**
Main changes:

1) Output frequencies from KerrGeoOrbitFunction as association
2) Return trajectories as pure functions
3) Add unit tests to check that "FastSpec" and "Analytic" methods agree on output trajectory.

I've also done a number of bug fixes to ensure those unit test were satisfied.

### CODE REVIEW

File: Kernel/KerrGeoOrbit.m [hunk 1]
```diff
@@ -56,10 +56,10 @@
 
 KerrGeoOrbitSchwarzDarwin[p_, e_] := Module[{t, r, \[Theta], \[Phi], assoc, consts, En,L,Q},
 
-t[\[Chi]_] := tSchwarzDarwin[p,e,\[Chi]];
-r[\[Chi]_] := rSchwarzDarwin[p,e,\[Chi]];
-\[Theta][\[Chi]_] := \[Theta]SchwarzDarwin[p,e,\[Chi]];
-\[Phi][\[Chi]_] := \[Phi]SchwarzDarwin[p,e,\[Chi]];
+t =Function[{Global`\[Chi]}, Evaluate[ tSchwarzDarwin[p,e,Global`\[Chi]] ], Listable];
+r =Function[{Global`\[Chi]}, Evaluate[ rSchwarzDarwin[p,e,Global`\[Chi]] ], Listable];
+\[Theta] =Function[{Global`\[Chi]}, Evaluate[ \[Theta]SchwarzDarwin[p,e,Global`\[Chi]] ], Listable];
```
Comment (barrywardell) [inline Kernel/KerrGeoOrbit.m:61]: What's the reason for putting \[Chi] in the global context here?

File: Kernel/KerrGeoOrbit.m [hunk 2]
```diff
@@ -925,20 +941,24 @@
...
-		\[CapitalDelta]tr[\[Lambda]_?NumericQ]:=0;
-		\[CapitalDelta]tr[\[Lambda]_List]:=\[CapitalDelta]tr[#]&/@\[Lambda];
-		\[CapitalDelta]\[Phi]r[\[Lambda]_?NumericQ]:=0;
-		\[CapitalDelta]\[Phi]r[\[Lambda]_List]:=\[CapitalDelta]\[Phi]r[#]&/@\[Lambda];
+		\[CapitalDelta]tr[\[Lambda]_(*?NumericQ*)]:=0;
+		(*\[CapitalDelta]tr[\[Lambda]_List]:=\[CapitalDelta]tr[#]&/@\[Lambda];*)
+		SetAttributes[\[CapitalDelta]tr,Listable];
+		\[CapitalDelta]\[Phi]r[\[Lambda]_(*?NumericQ*)]:=0;
+		(*\[CapitalDelta]\[Phi]r[\[Lambda]_List]:=\[CapitalDelta]\[Phi]r[#]&/@\[Lambda];*)
+		SetAttributes[\[CapitalDelta]\[Phi]r,Listable]
```
Comment (barrywardell) [inline Kernel/KerrGeoOrbit.m]: I would suggest just removing, rather than commenting out code here (and elsewhere).

**Review by barrywardell — COMMENTED** [review]
Just a couple of minor comments/questions, but otherwise everything looks fine to me.

File: Kernel/KerrGeoOrbit.m (hunk 1 above)
Comment (MvdMeent) [reply Kernel/KerrGeoOrbit.m:61]: [Chi] is a named dummy variable of the function. If you don't use a symbol in the Global` context, the output will be much harder to read, and because it is just a dummy there are no side effects to the global context.

File: Kernel/KerrGeoOrbit.m (hunk 2 above)
Comment (MvdMeent) [reply Kernel/KerrGeoOrbit.m]: Before doing that, I wanted to ask one of the Chapel Hill guys what the purpose of restricting these definitions to numerical values only was. There might be something I am missing.

Comment (znasipak) [reply Kernel/KerrGeoOrbit.m]: For the spectral integration/Fourier sums I restricted the functions to numerical values because the series output could be unwieldy if you gave it a variable as input. I figured if people wanted analytic forms they would not be using the spectral method. I do not think that removing this restriction should break anything, but I would need to double check. If you all think it would be good to remove this restriction I can go in and make that change.

Comment (MvdMeent) [reply Kernel/KerrGeoOrbit.m]: Thanks @znasipak . Related question, is the ability to thread these functions over lists used anywhere internally? If not, we can drop setting the Listable attribute for these intermediate results. (The pure functions outputted at the end for the trajectory are already set to be listable.)

**Comment by MvdMeent** [comment]
@barrywardell Can you see where the unit tests failed? (I can't access the Jenkins output.) Did I screw up the unit tests I added?

**Comment by nielsw2** [comment]
It looks like a test was running for a very long time (and was then aborted). I see @barrywardell has added a time out to the master branch but not this one. I'm sure we can give you access to Jenkins.

**Comment by barrywardell** [comment]
The tests appeared to get stuck for some unknown reason and I manually cancelled the job. I added a timeout on the master branch and have just now merged that change into this branch.

**Comment by MvdMeent** [comment]
I fixed (hopefully) the unit tests.

File: Kernel/KerrGeoOrbit.m (hunk 2 above)
Comment (znasipak) [reply Kernel/KerrGeoOrbit.m]: @MvdMeent This is a relic of past versions of the code where the Listable attribute was not set for the functions that were returned by KerrGeoOrbit. If the pure functions provide this attribute then I think you are right and we can drop this setting for the intermediate result.

**Comment by barrywardell** [comment]
There's still one test failing, but it appears to be a numerical tolerance issue.  Here's the test and resulting values:

```Mathematica
Block[{Internal`$EqualTolerance = 4, a = 0.9, p = 10., e = 0.5, x = 0.5}
, {KerrGeoOrbit[a, p, e, x, Method -> "Analytic", "Parametrization" -> "Mino"][4
2.], KerrGeoOrbit[a, p, e, x, Method -> "FastSpec", "Parametrization" -> "Mino"]
[42.]}]

{{7150.814713321447, 6.714658737192933, 2.096691530803767, 161.12599744329108}, 
 {7150.814712254346, 6.714658737192922, 2.0966915308037866, 161.12599748541558}}
```

**Comment by MvdMeent** [comment]
Yes, that seems a tolerance issue. It passed on my machine, but the numerical errors could vary by machine or platform. We can just increase the tolerance for the test.

**Comment by barrywardell** [comment]
The tests run with Mathematica 11.3.0 on Linux. I found that increasing the tolerance to 6.375 for that test fixes it. This corresponds to an error in approximately the 10th digit. I guess that's acceptable?

**Comment by MvdMeent** [comment]
> 
> 
> The tests run with Mathematica 11.3.0 on Linux. I found that increasing the tolerance to 6.375 for that test fixes it. This corresponds to an error in approximately the 10th digit. I guess that's acceptable?

Yep.

File: Kernel/KerrGeoOrbit.m (hunk 1 above)
Comment (barrywardell) [reply Kernel/KerrGeoOrbit.m:61]: Sounds reasonable. Is it expected that these pure functions would be publicly visible? Would it be better to have them as nicely formatted objects?

Comment (MvdMeent) [reply Kernel/KerrGeoOrbit.m:61]: Probably. Have a nicely formatted form of the output, would be nice. (But not essential.)

**Comment by barrywardell** [comment]
The tests are all passing now.
